development:
  domain: localhost:3000

test:
  domain: test.host

production:
  domain: minitodo.heroku.com


all:
  version: 0.9a
  name: 'MiniTodo'
  description: Yet another ToDo Application with lots of tags.
